#!/bin/sh

##############################################################################
#
#  Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

app_path=
while
    APP_HOME=expr "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jar{app_path}" : "\(.*\)/" || true
    [ -h "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarapp_path" ]
do
    ls=ls -ld "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarapp_path"
    link=expr "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarls" : '.*-> \(.*\)$'
    case C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarlink in
      /*)   app_path=C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarlink ;;
      *)    app_path=C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarAPP_HOMEC:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarlink ;;
    esac
done

APP_HOME=cd "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jar{APP_HOME:-./}" && pwd -P || exit

APP_NAME="Gradle"
APP_BASE_NAME=asename "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jar0"

DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

CLASSPATH=C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarAPP_HOME/gradle/wrapper/gradle-wrapper.jar

if [ -n "" ] ; then
    if [ -x "/jre/sh/java" ] ; then
        JAVACMD=/jre/sh/java
    else
        JAVACMD=/bin/java
    fi
    if [ ! -x "" ] ; then
        echo "ERROR: JAVA_HOME is set to an invalid directory: "
        exit 1
    fi
else
    JAVACMD=java
    which java >/dev/null 2>&1 || { echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."; exit 1; }
fi

exec "" C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarDEFAULT_JVM_OPTS C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarJAVA_OPTS C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarGRADLE_OPTS "-Dorg.gradle.appname=C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarAPP_BASE_NAME" -classpath "C:\Users\Masoud\Downloads\Taranik 60\gradle\wrapper\gradle-wrapper.jarCLASSPATH" org.gradle.wrapper.GradleWrapperMain "$@"
